# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ECGWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.096, y1:0.017, x2:0.846591, y2:1, stop:0 rgba(115, 255, 185, 255), stop:1 rgba(162, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.loadButton.sizePolicy().hasHeightForWidth())
        self.loadButton.setSizePolicy(sizePolicy)
        self.loadButton.setMinimumSize(QtCore.QSize(0, 40))
        self.loadButton.setStyleSheet("QPushButton {background-color: qlineargradient(spread:pad, x1:0.568, y1:1, x2:0.522727, y2:0, stop:0 rgba(0, 182, 190, 255), stop:1 rgba(158, 255, 210, 255));\n"
"color: black;\n"
"font-size: 18px;\n"
"font: bold;\n"
"border: 1px solid blue;\n"
"border-radius: 10px;}\n"
"\n"
"QPushButton:pressed {background-color: qlineargradient(spread:pad, x1:0.562318, y1:1, x2:0.522727, y2:0, stop:0 rgba(6, 255, 192, 255), stop:1 rgba(74, 120, 69, 255));\n"
"color: white;\n"
"font-size: 18px;\n"
"font: bold;\n"
"border-radius: 10px;\n"
"border: 1px outset rgb(205, 255, 229);}\n"
"\n"
"QPushButton:hover:!pressed {background-color:qlineargradient(spread:pad, x1:0.522, y1:0, x2:0.511636, y2:1, stop:0 rgba(84, 76, 95, 255), stop:1 rgba(64, 233, 186, 255));\n"
"color: black;\n"
"font-size: 18px;\n"
"font: bold;\n"
"border: 1px solid blue;\n"
"border-radius: 10px;}\n"
"")
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.predictButton.sizePolicy().hasHeightForWidth())
        self.predictButton.setSizePolicy(sizePolicy)
        self.predictButton.setMinimumSize(QtCore.QSize(0, 40))
        self.predictButton.setBaseSize(QtCore.QSize(0, 50))
        self.predictButton.setStyleSheet("QPushButton {background-color: qlineargradient(spread:pad, x1:0.568, y1:1, x2:0.522727, y2:0, stop:0 rgba(0, 182, 190, 255), stop:1 rgba(158, 255, 210, 255));\n"
"color: black;\n"
"font-size: 18px;\n"
"font: bold;\n"
"border: 1px solid blue;\n"
"border-radius: 10px;}\n"
"\n"
"QPushButton:pressed {background-color: qlineargradient(spread:pad, x1:0.562318, y1:1, x2:0.522727, y2:0, stop:0 rgba(6, 255, 192, 255), stop:1 rgba(74, 120, 69, 255));\n"
"color: white;\n"
"font-size: 18px;\n"
"font: bold;\n"
"border-radius: 10px;\n"
"border: 1px outset rgb(205, 255, 229);}\n"
"\n"
"QPushButton:hover:!pressed {background-color:qlineargradient(spread:pad, x1:0.522, y1:0, x2:0.511636, y2:1, stop:0 rgba(84, 76, 95, 255), stop:1 rgba(64, 233, 186, 255));\n"
"color: black;\n"
"font-size: 18px;\n"
"font: bold;\n"
"border: 1px solid blue;\n"
"border-radius: 10px;}\n"
"")
        self.predictButton.setObjectName("predictButton")
        self.horizontalLayout.addWidget(self.predictButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.predictionLabel = QtWidgets.QLabel(self.centralwidget)
        self.predictionLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.predictionLabel.sizePolicy().hasHeightForWidth())
        self.predictionLabel.setSizePolicy(sizePolicy)
        self.predictionLabel.setMinimumSize(QtCore.QSize(0, 45))
        self.predictionLabel.setStyleSheet("font-size: 16px; font: bold; color: blue; background-color: rgba(0,0,0,0%); ")
        self.predictionLabel.setText("")
        self.predictionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.predictionLabel.setObjectName("predictionLabel")
        self.gridLayout.addWidget(self.predictionLabel, 3, 1, 1, 1)
        self.mainTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.mainTitle.sizePolicy().hasHeightForWidth())
        self.mainTitle.setSizePolicy(sizePolicy)
        self.mainTitle.setMinimumSize(QtCore.QSize(0, 40))
        self.mainTitle.setStyleSheet("color: black;\n"
"font-size: 18px;\n"
"background-color:rgba(0, 255, 123, 120);\n"
"font: bold;\n"
"border: 1px solid red;\n"
"border-radius: 10px")
        self.mainTitle.setTextFormat(QtCore.Qt.AutoText)
        self.mainTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.mainTitle.setObjectName("mainTitle")
        self.gridLayout.addWidget(self.mainTitle, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.ecgImage = QtWidgets.QLabel(self.centralwidget)
        self.ecgImage.setMinimumSize(QtCore.QSize(432, 288))
        self.ecgImage.setStyleSheet("background-color: white")
        self.ecgImage.setText("")
        self.ecgImage.setObjectName("ecgImage")
        self.gridLayout.addWidget(self.ecgImage, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Классификатор ЭКГ"))
        self.loadButton.setText(_translate("MainWindow", "Загрузить изображение"))
        self.predictButton.setText(_translate("MainWindow", "Классифицировать"))
        self.mainTitle.setText(_translate("MainWindow", "Классификатор ЭКГ"))
